### ISSUE TITLE
ES syntax highlighting

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#125]
https://twitter.com/ronkorving/status/690469192190070788

**Comment by revin** [comment]
Our [highlights](https://www.npmjs.com/package/highlights) dependency does JS highlighting via [language-javascript](https://github.com/atom/language-javascript), but it's currently submoduled in at a commit that's a year old. If I pull in the latest language-javascript and run it against the linked [README](https://raw.githubusercontent.com/Wizcorp/express-rested/master/README.md) I get much better rendered HTML.

I don't know if newww will already have the styles necessary to make it look nice, but for marky it looks like the solution is to get `highlights` to update that dependency (I'm guessing they could *all* stand to be updated). I'll file a PR over there.

**Comment by ashleygwilliams** [comment]
you, as always, are the best @revin -- mind cc/ing me on the issue/PR so i can follow?

**Comment by revin** [comment]
Sure thing; the PR is https://github.com/atom/highlights/pull/34.

If it's accepted, it does break one of our tests, because we specifically [test for the presence of the `modifier` class](https://github.com/npm/marky-markdown/blob/master/test/index.js#L71) on rendered output, but somewhere along the line it got changed to `type`.

There are some other small additions, like `keyword operator js` changes to `keyword operator assignment js`, functions get wrapped/decorated with more classes, and stuff like that. Whether or not those are backwards compatible depends on how the CSS formatting them is written, I guess.

**Comment by revin** [comment]
oh also so I don't forget, this will require a rebuild of the stuff in `highlights-tokens`

**Comment by ronkorving** [comment]
Turns out the issue was with tab-indentation. I changed to spaces, and all renders well now.

**Comment by revin** [comment]
Thanks @ronkorving! Yeah, we've got work in progress on fixing the tab indentation issue as well (in #127), I should've recognized it here too but I guess I was distracted too much on the lack of highlighting on the new keywords, etc... 😁

**Comment by ashleygwilliams** [comment]
have bumped @bcoe to try to help on the highlights end :)

**Comment by ashleygwilliams** [comment]
closed by 6a9c64df3ca5c3e1dad8e79e120aadb2ab684845
