### ISSUE TITLE
html comments are removed from code blocks

### ISSUE THREAD

**Issue by psalaets** [npm/marky-markdown#14]
This causes some readme's to look odd on npmjs.com.

It looks like all html comments are regex'd out before the markdown parser is run ([see index.js](https://github.com/npm/marky-markdown/blob/master/index.js#L47)).

If the `sanitize` option is set (true by default), marky-markdown runs sanitize-html which [removes html comments](https://github.com/punkave/sanitize-html/issues/38) as well.

**Comment by psalaets** [comment]
The 2nd part above doesn't really matter because html comments in code blocks will be

```&lt;!-- blah --&gt;```

before sanitize-html sees them

**Comment by zeke** [comment]
Bummer. I added the comment removal because the comments in some READMEs were causing `marked` to crash. Perhaps swapping out the markdown parser will help... see https://github.com/markdown-it/markdown-it/issues/40

I'll keep an eye on https://github.com/punkave/sanitize-html/issues/38 too. Thanks for reporting.

**Comment by puzrin** [comment]
In `markdown-it` there are no problems with hangs. But HTML is disabled by default. You can enable HTML, but you should use external sanitizer then.

**Comment by zeke** [comment]
Thanks for the tip, @puzrin!

**Comment by psalaets** [comment]
Fixed by 16696d206dd95e3594a0dbcdbf20271cffaa71d3
