### ISSUE TITLE
Allowing <dl> elements

### ISSUE THREAD

**Issue by nwhetsell** [npm/marky-markdown#169]
It appears that [npmjs.com](https://npmjs.com) doesn’t allow [`<dl>` elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl). Also, a `<dl>` element that is a descendant of another `<dl>` seems to have some of its content enclosed in a `<pre>` element.

Here’s a screenshot of an example from https://github.com/nwhetsell/csound-api#ParseOrc:

<img width="468" alt="screen shot 2016-03-28 at 8 58 54 am" src="https://cloud.githubusercontent.com/assets/14102861/14078384/6c13f1e4-f4c3-11e5-8681-e711404af027.png">

And here’s the same content at https://www.npmjs.com/package/csound-api#ParseOrc:

<img width="497" alt="untitled" src="https://cloud.githubusercontent.com/assets/14102861/14078447/e188472c-f4c3-11e5-831b-f2e7967f2048.png">

I’m not sure how common `<dl>` elements are in Markdown, but it would be great if they could be supported.

**Comment by revin** [comment]
Hi @nwhetsell, thanks for writing this up; nice find! It seems as though you've hit a combination of two things here. Well, three:

1. The first problem is that markdown still has no standard way of representing a definition/description list. You know this, of course, which is why you're added them directly as inline HTML. (I found a [discussion](http://talk.commonmark.org/t/description-list/289) from a couple of years back that indicates a lot of markdown parsers have made a kind of _de facto_ standard out of a particular syntactical construct, but GitHub Flavored Markdown doesn't support it)
2. Our parser is seeing the `<dl>` et al and interpreting the whole thing as inline HTML like it should, but our [sanitizer module](https://github.com/npm/marky-markdown/blob/master/lib/sanitize.js) is clobbering them, which is why they don't appear in the rendered document on npmjs.com.
3. Since the parser is interpreting it as inline HTML, it has no concept of anything being "nested" (i.e., the current nesting level is zero the whole way through your list), so when it sees lines with a leading four space indent, it's doing the standardized CommonMark thing and interpreting them as a code block. That's where the `<pre>` wrapper is coming from.

The smallest solution here is for us to:

* add `<dl>`, `<dt>`, `<dd>` in the sanitizer's whitelist
* get the parser to recognize the difference between nested inline HTML and a markdown code block

I'll make the sanitizer change for the next release, and I'll add an item to my todo list for the second part; in the meantime, you can work around that part by unindenting those lines (not that it really helps anything until the sanitizer is updated).

**Comment by nwhetsell** [comment]
Many thanks!

**Comment by revin** [comment]
fixed in #170.
