### ISSUE TITLE
links not wrapped in <p> when h3 is html.

### ISSUE THREAD

**Issue by jdalton** [npm/marky-markdown#217]
I noticed that

```
### foo
[a](foo) [b](bar)
```

generates html like:

```
<h3>foo</h3>
<p>
<a href="foo">a</a> <a href="bar">b</a>
</p>
```

but

```
<h3 id="baz">foo</h3>
[a](foo) [b](bar)
```

generates html like:

```
<h3 id="baz">foo</h3>
<a href="foo">a</a> <a href="bar">b</a>
<p></p>
```

**Comment by revin** [comment]
Hey @jdalton thanks for writing this up! 👍 

CommonMark has some interesting handling rules for HTML. The section on [HTML blocks](http://spec.commonmark.org/0.25/#html-blocks) describes the conditions in which some markup is considered an "HTML Block", and even though `<h3>` is a block-level tag, it's not in the list of tag names that create HTML Blocks, so it gets parsed as [raw HTML](http://spec.commonmark.org/0.25/#raw-html) instead, which means

    <h3 id="baz">foo</h3>
    [a](foo) [b](bar)

_should_ render as

    <p><h3 id="baz">foo</h3>
    <a href="foo">a</a> <a href="bar">b</a></p>

i.e., the wrapping `<p>` should wrap the entire thing, and it does, in the [markdown-it demo](https://markdown-it.github.io/). For some reason we have the empty trailing `<p>` instead. So that's strange.

However, it might be irrelevant, because this is an area where GitHub renders the perhaps more intuitive way it looks like you're expecting, so if we're going to change anything, it should probably be in that (non-standard) direction, yeah?

**Comment by revin** [comment]
An interesting related thing I discovered while looking at this is that `<h1>` _is_ in the list of tag names that create HTML Blocks, so if it was an `<h1>` here rather than `<h3>`, the markdown is considered to be part of the HTML Block, and [doesn't get translated to HTML at all](http://spec.commonmark.org/0.25/#example-126), unless you put a blank line in between (the blank line terminates the HTML Block).

**Comment by jamestautges** [comment]
#278 should fix this. I had to write a plugin for the markdown-it parser to circumvent it treating the header as inline html.

**Comment by revin** [comment]
#278 is merged; closing
