### ISSUE TITLE
Relative image URL's are not converted.

### ISSUE THREAD

**Issue by MichMich** [npm/marky-markdown#306]
Hi Guys, first of all thanks for this awesome package!

I'm trying to use this lib to display some Readme files on a site I'm currently working on. Unfortunately, all the image links I test are broken. The documentation of this package states:

> Converts relative GitHub images sources to their GitHub raw equivalents.

So if I'm not mistaken, this is not the desired outcome.

For example, the following README contains a header image: 
https://raw.githubusercontent.com/MichMich/MagicMirror/master/README.md

````
![MagicMirror²: The open source modular smart mirror platform. ](.github/header.png)
````
Marky-Markdown converts this into the following html:
````
<img src=".github/header.png" alt="MagicMirror²: The open source modular smart mirror platform. ">
````

Which leaves me with a broken image link om my site's server.

FYI, I use the client-side (browser) version of Marky-Markdown with the following configuration:

````
var html = marky(markdown, {
    highlightSyntax: false,
});
````

Any idea what I'm doing wrong? Thanks!

**Comment by revin** [comment]
Hi @MichMich, my guess is that it's because you're not passing the package information into marky. The ["npm packages"](https://github.com/npm/marky-markdown/tree/9ec75b4fab46c1cef84f9cb513aee7c123dee100#npm-packages) section of the readme describes it, or you can check out the [unit tests](https://github.com/npm/marky-markdown/blob/9ec75b4fab46c1cef84f9cb513aee7c123dee100/test/repo-github.js#L8-L20) for a quick example.

**Comment by MichMich** [comment]
Sometimes solutions are so simple ... I totally missed that part.

Thanks a lot!
