### ISSUE TITLE
Continues to parse markdown as inline HTML when there is no blank line between them

### ISSUE THREAD

**Issue by jefflembeck** [npm/marky-markdown#317]
Cross-post from @avrahams  https://github.com/npm/www/issues/61

The **_bold & italic_** notation is not shown correctly in npm 
https://help.github.com/articles/basic-writing-and-formatting-syntax/#styling-text

See [IoT virtual device module page](https://www.npmjs.com/package/node-red-contrib-iot-virtual-device)

in npm
![image](https://cloud.githubusercontent.com/assets/8184528/20135670/99520804-a679-11e6-8080-5f16764d19e3.png)

in github
![image](https://cloud.githubusercontent.com/assets/8184528/20135699/b9351422-a679-11e6-9a82-81e0386d687d.png)

**Comment by revin** [comment]
Thanks @jefflembeck.

OK so here the issue is the inline HTML for the `<img>` gets interpreted per CommonMark as an HTML block, and that doesn't terminate until there's a blank line. So to match GitHub we need to figure out how to make markdown-it parse this as inline HTML followed by a markdown list, or perhaps more generally, figure out how to know when we should switch back into "markdown parsing mode" (not a real thing under the hood, just logically what's happening) even when there's no terminating blank line.

For reference, here's the markdown:

```markdown
### Nodes
<img src="https://developer.ibm.com/iotplatform/wp-content/uploads/sites/24/2016/10/Virtual-IoT-Device.png"/>
- **_Device Schema_** (configuration node) to define the device type
- **_Start Device_** to create a new instance of a device type
- **_Generate Event_** to send events to the IoT platform
- **_Set Properties_** to set properties of a device instance 
- **_Device Function_** to write customized behavior using a specific device instance properties
- **_Device Listener_** to react on changes in device instances state (e.g. property change)
```
