### ISSUE TITLE
Huge whitespace gaps

### ISSUE THREAD

**Issue by machellerogden** [npm/marky-markdown#340]
The README for one of my packages displays with large whitespace gaps when viewed on npmjs.com but looks great on github: https://www.npmjs.com/package/bitcar

Thoughts? I'm happy to dig in and contribute a fix if someone can point me in the right direction.

**Comment by machellerogden** [comment]
See also, github output of same markdown: https://github.com/carsdotcom/bitcar

**Comment by revin** [comment]
Hey @machellerogden, interesting find! I'd say this is a bug on the npm site; your code snippets are being rendered without syntax highlighting, so the CSS over there for `pre code` has `margin: 0 0 215px 0;` and that's what's creating the giant vertical spacing.

There are a couple of things to do here:
1. Suggest filing a bug against the [web site](https://github.com/npm/www) for this. (or @ashleygwilliams wanna do it?)
2. For technical internal markdown engine reasons, code blocks indented with four spaces are treated slightly differently than code blocks marked by the triple backtick fence syntax; you could try switching to a fence, since npm's CSS for that doesn't have the huge margin (fenced code blocks have syntax highlighting applied, and that changes the rendered output)

So:
````
# Don't do this

    $ some_command
    $ another --command --here

# Do this instead

```
$ some_command
$ another --command --here
```
````

I realize it doesn't look as good when you read the markdown in a raw text editor, but that's the solution you can apply right now 😕 at least until the CSS is fixed.

**Comment by revin** [comment]
oh, haha, you already filed it :) https://github.com/npm/www/issues/124

I'll go ahead and close this one since the other repo is where this issue belongs; feel free to reopen it if there's a question about the HTML generation, or how marky-markdown works internally, or whatever. Thanks!

**Comment by machellerogden** [comment]
Thanks! Changing my markdown in the meantime has resolved the issue for me. I'll follow up with npm
