### ISSUE TITLE
list items containing square brackets with no subsequent parens just disappear

### ISSUE THREAD

**Issue by SheetJSDev** [npm/marky-markdown#390]
Using 10.1.4 (the latest version on NPM right now) against https://github.com/SheetJS/js-xlsx/blob/master/docbits/98_reference.md:

```markdown
 - [MS-XLSX]: Excel (.xlsx) Extensions to the Office Open XML SpreadsheetML File Format
 - [MS-OE376]: Office Implementation Information for ECMA-376 Standards Support
```

The github preview shows both lines:

<img width="694" alt="screen shot 2017-06-08 at 11 44 25" src="https://user-images.githubusercontent.com/6070939/26937618-d9c3fce6-4c3f-11e7-821a-0b925d30698c.png">

However the generated HTML shows a blank line for the second case:

```html
<li>[MS-XLSX]: Excel (.xlsx) Extensions to the Office Open XML SpreadsheetML File Format</li>
<li></li>
```

If you want to see this in the NPM website, the [xlsx README.md](https://www.npmjs.com/package/xlsx#references) is missing the same set of entries:

<img width="594" alt="screen shot 2017-06-08 at 11 46 20" src="https://user-images.githubusercontent.com/6070939/26937714-2190acb8-4c40-11e7-8f8e-3747327406b7.png">

Interestingly, the lines with square brackets and with parentheses are preserved, even though they do not correspond to a link.

**Comment by revin** [comment]
Hi @SheetJSDev, very interesting. I can't think off the top of my head what might cause this, but we'll definitely get to the bottom of it.

**Comment by SheetJSDev** [comment]
This is still an issue in `11.2.0`.  FWIW the workaround of escaping the opening square brackets appears to work.

**Comment by daphee** [comment]
I investigated a little and found the source of the bug: the `override-link-destination-parser.js` plugin.

This plugin alters the part of `markdown-it` that parses the *target* portion of a link to allow spaces in links.

The problem is that CommonMark includes syntax to apply a label to a link in order to be able to replace the full link by just the label in other parts of the text. (e.g. see this [example](http://spec.commonmark.org/0.28/#example-168))

This syntax is available in lists as well, apparently. So even CommonMark (and GH) suffer from same bug but only for lists with one word after the `[...]` part.

 - [MS-XLSX]: Excel 
 - [MS-OE376]: Office

The above list was created with this: (you can also try it [here](http://spec.commonmark.org/dingus/?text=%20-%20%5BMS-XLSX%5D%3A%20Excel%20%0A%20-%20%5BMS-OE376%5D%3A%20asf))

```
 - [MS-XLSX]: Excel 
 - [MS-OE376]: Office
```

I am not sure how to fix this. Currently the altered `parseLinkDestination` consumes the whole line. So from the perspective of markdown-it it is a perfectly fine definition of a reference, constisting of `[<text>]: <link><EOL>`. 

The reason why in the above example some lines are displayed is because those contain parentheses. In those cases the altered `parseLinkDestination` doesn't consume the whole line but stops at the parenthesis. While parsing the remaining text markdown-it recognizes that it isn't a valid definition of a reference.

**Comment by SheetJSDev** [comment]
@daphee thanks for looking into this!

It does seem like a quirk in the CommonMark processing, like in this test:

<img width="705" alt="screen shot 2017-10-30 at 17 13 59" src="https://user-images.githubusercontent.com/6070939/32196060-c1af7960-bd95-11e7-8a7b-ab310da3e140.png">

http://spec.commonmark.org/dingus/?text=%20-%20%5Bsquare%5D%3A%20%0A%20-%20%5Bsquare%5D%3A%20(paren)%0A%20-%20%5Bsquare%5D%3A%20pre%20(paren)%0A%20-%20%5Bsquare%5D%3A%20(paren)%20post%0A%20-%20%5Bsquare%5D%3A%20pre%20(paren)%20post

On our end, the offending lines were replaced with something that wouldn't elicit the issue.
