### ISSUE TITLE
Support footnotes?

### ISSUE THREAD

**Issue by thecristen** [npm/marky-markdown#403]
I didn't see an issue for this already, but I think it'd be great if this parser supported the usage of footnotes.

As a point of reference, [markdown-it](https://github.com/markdown-it/markdown-it-footnote) has a plugin that does this.

**Comment by revin** [comment]
Hi @thecristen thanks for the question! To my knowledge GitHub Flavored Markdown doesn't support footnotes, is that correct? I created a [test gist](https://gist.github.com/revin/e4cb2806b5b2289703af34e14baf4fef) to check, and it doesn't seem to know what to do with them. The only mention of footnotes in the [GFM spec](https://github.github.com/gfm/) is in the introduction, where it talks about certain extensions of markdown supporting them.

Since marky's goal is to be a JS implementation of GFM, supporting footnotes would be a non-goal for the project. However! If you're using marky programmatically, we have a `getParser()` method (see [the docs](https://github.com/npm/marky-markdown/tree/74fe6f7d1e04f392096f4e3e8a694a77f583dd57#low-level-parser-access)  that can give you access to the internal markdown-it instance. You could use that and add the plugin that way.

Does that help? If not, or if I've gotten something wrong (happens every single day! 😛 ), please let me know.
