### ISSUE TITLE
SVG in headers

### ISSUE THREAD

**Issue by e-oj** [npm/marky-markdown#423]
Why are svg tags generated in headers? is there a way to turn this behavior off? It leads to a lot of unnecessary white space in the browser.

**Comment by revin** [comment]
Hey @e-oj, how's it going? Thanks for asking!

Marky's goal is to be a JavaScript implementation of the renderer used by GitHub for markdown documents. Since GitHub renders those SVG icons in headers (it's the link icon that shows up when you hover the mouse cursor over the heading text), we do the same.

If you don't need them for your use case, this behavior is configurable. Pass [`enableHeadingLinkIcons: false`](https://github.com/npm/marky-markdown/tree/cf7ca92c465aa70c848a292ff8f0db354247c374#options) in the options when rendering your document, and it turns this feature off.

Cheers! 🎉

**Comment by e-oj** [comment]
Cool. thanks. 👍 👍
