### ISSUE TITLE
Remove unused frontmatter-to-meta-tag code

### ISSUE THREAD

**Issue by zeke** [npm/marky-markdown#43]
We're not actually using the generated meta tags, and it's causing problems: https://github.com/npm/newww/issues/850

**Comment by zeke** [comment]
See also http://c2.com/cgi/wiki?YouArentGonnaNeedIt

**Comment by ashleygwilliams** [comment]
is this still an issue? if you can confirm lemme know. we'll aim to fix this in 5.7
cc @rwaldron @zeke

**Comment by revin** [comment]
I think the problem with johnny-five's readme was actually solved by an [edit they made themselves](https://github.com/rwaldron/johnny-five/commit/891835f8cfc6306721c2254ff482fbb3b1c2bf2d#diff-04c6e90faac2675aa89e2176d2eec7d8R1). If you run marky on the older version of the readme prior to that commit, we still treat the leading comment as frontmatter, so from what I can see, yes, we still have an issue here; it generates:

```html
<meta name="Hello! Please don&apos;t edit this file! If you&apos;d like to make changes to the readme contents, please make them in the tpl/.readme.md file. If you&apos;d like to add an example" content="1. Add the file in `eg/` 2. Add a breadboard image in `docs/breadboards` 3. Add an entry to `tpl/programs.json`. 4. Generated the markdown with: `grunt examples`">
```

Does *anyone* use the meta tags? If not, since we've got a few breaking changes lined up and ready to merge, we can chuck the frontmatter code.

**Comment by rwaldron** [comment]
Thanks @revin!
