### ISSUE TITLE
README h1s not stripped for scoped packages

### ISSUE THREAD

**Issue by sindresorhus** [npm/marky-markdown#48]
https://www.npmjs.com/package/@sindresorhus/df

Not sure why. Maybe because of the short header.

**Comment by zeke** [comment]
Are you saying you expected the `# df` H1 line from your readme to be hidden?

**Comment by sindresorhus** [comment]
Yes

**Comment by ashleygwilliams** [comment]
Adding this to `5.7`.

**Comment by revin** [comment]
Is it because the scope name wrecks the [similarity calculation](https://github.com/npm/marky-markdown/blob/master/lib/packagize.js#L14-L15)? I've got a change locally that also tests the similarity of the H1 to the package name sans scope, but I'm having trouble finding any other scoped packages in the NPM registry to test against. @ashleygwilliams do you know how I can get a list of a few?

**Comment by ashleygwilliams** [comment]
ooh @revin i think you are on to something there. p sure that is :100: it.
here's another example: https://www.npmjs.com/package/@aredridel/redis-mock

**Comment by ashleygwilliams** [comment]
@sindresorhus think we've found the source of the issue. ideally the fix will ship with 7.0.0 and be on npmjs.com shortly after.

**Comment by revin** [comment]
Thanks @ashleygwilliams, that helped. PR is #103, tiny update ftw I guess 😜

**Comment by ashleygwilliams** [comment]
fixed in https://github.com/npm/marky-markdown/pull/103, closing
